# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-sanbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-sanbox
  template:
    metadata:
      labels:
        app: quarkus-sanbox
    spec:
      containers:
        - name: quarkus-sanbox
          image: acevedor/IMAGE_TO_OVERRIDE:TAG
          imagePullPolicy: Always
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
